<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>${groupId}</groupId>
        <artifactId>${rootArtifactId}</artifactId>
        <version>${version}</version>
    </parent>
    <artifactId>${artifactId}</artifactId>
    <name>${artifactId}</name>
    <description>Demo Rest OpenApi Model layer</description>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>0.2.10</version>
        </dependency>
        <dependency>
            <groupId>tools.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-xml</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
            <version>${springdoc.openapi.starter.webmvc.ui.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.16.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/api-docs.yaml</inputSpec>
                            <output>${project.build.directory}/generated-sources</output>
                            <generatorName>spring</generatorName>
                            <apiPackage>resources</apiPackage>
                            <modelPackage>model</modelPackage>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <templateResourcePath>${project.basedir}/src/template</templateResourcePath>
                            <apisToGenerate>users</apisToGenerate>
                            <modelsToGenerate>Role,User</modelsToGenerate>
                            <skip>false</skip>
                            <schemaMappings>
                                <schemaMapping>ProblemDetail=org.springframework.http.ProblemDetail</schemaMapping>
                            </schemaMappings>
                            <configOptions>
                                <generatedConstructorWithRequiredArgs>false</generatedConstructorWithRequiredArgs>
                                <useSpringBoot4>true</useSpringBoot4>
                                <useJakartaEe>true</useJakartaEe>
                                <useJackson3>true</useJackson3>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <skipIfSpecIsUnchanged>true</skipIfSpecIsUnchanged>
                                <interfaceOnly>true</interfaceOnly>
                                <requestMappingMode>api_interface</requestMappingMode>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
